"""initial schema

Revision ID: 00c0ddea80b6
Revises: 
Create Date: 2026-06-10 22:52:38.928986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c0ddea80b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gdpr_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='app'
    )
    op.create_table('institutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inst_type', sa.String(), nullable=True),
    sa.Column('competence', sa.Text(), nullable=True),
    sa.Column('default_term_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('coverage_status', sa.String(), nullable=True),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('project_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_procedure_set', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_type_id', sa.String(), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['municipality_id'], ['core.municipalities.id'], ),
    sa.ForeignKeyConstraint(['project_type_id'], ['core.project_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issuer_institution_id', sa.String(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issuer_institution_id'], ['core.institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('normative_acts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('act_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_id'], ['core.municipalities.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['core.normative_acts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('stripe_payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('project_params',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('param_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'param_name'),
    schema='app'
    )
    op.create_table('project_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_sub_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('procedures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('output_document_id', sa.String(), nullable=True),
    sa.Column('statutory_term_days', sa.Integer(), nullable=True),
    sa.Column('act_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['core.normative_acts.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['core.institutions.id'], ),
    sa.ForeignKeyConstraint(['output_document_id'], ['core.documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('project_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('planned_duration_days', sa.Integer(), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_start_day', sa.Integer(), nullable=True),
    sa.Column('computed_end_day', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['core.procedures.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('dependencies',
    sa.Column('successor_id', sa.String(), nullable=False),
    sa.Column('predecessor_id', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['predecessor_id'], ['core.procedures.id'], ),
    sa.ForeignKeyConstraint(['successor_id'], ['core.procedures.id'], ),
    sa.PrimaryKeyConstraint('successor_id', 'predecessor_id'),
    schema='core'
    )
    op.create_table('fee_tariffs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('procedure_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('act_id', sa.String(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['core.normative_acts.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['core.municipalities.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['core.procedures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('procedure_inputs',
    sa.Column('procedure_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['core.documents.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['core.procedures.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'document_id'),
    schema='core'
    )
    op.create_table('rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('param_name', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_procedure_id', sa.String(), nullable=True),
    sa.Column('target_institution_id', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['target_institution_id'], ['core.institutions.id'], ),
    sa.ForeignKeyConstraint(['target_procedure_id'], ['core.procedures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.users.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['app.project_nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('project_fees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('fee_tariff_id', sa.String(), nullable=True),
    sa.Column('basis_value', sa.Float(), nullable=True),
    sa.Column('computed_amount', sa.Float(), nullable=True),
    sa.Column('act_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['fee_tariff_id'], ['core.fee_tariffs.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['app.project_nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_fees', schema='app')
    op.drop_table('events', schema='app')
    op.drop_table('rules', schema='core')
    op.drop_table('procedure_inputs', schema='core')
    op.drop_table('fee_tariffs', schema='core')
    op.drop_table('dependencies', schema='core')
    op.drop_table('project_nodes', schema='app')
    op.drop_table('procedures', schema='core')
    op.drop_table('subscriptions', schema='app')
    op.drop_table('project_versions', schema='app')
    op.drop_table('project_params', schema='app')
    op.drop_table('orders', schema='app')
    op.drop_table('normative_acts', schema='core')
    op.drop_table('documents', schema='core')
    op.drop_table('projects', schema='app')
    op.drop_table('project_types', schema='core')
    op.drop_table('municipalities', schema='core')
    op.drop_table('institutions', schema='core')
    op.drop_table('users', schema='app')
    # ### end Alembic commands ###
