"""validation_requests

Revision ID: fa5f60d33312
Revises: 6b943d6c0044
Create Date: 2026-06-12 08:24:34.059780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5f60d33312'
down_revision: Union[str, Sequence[str], None] = '6b943d6c0044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='requested', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('certified_pdf_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['app.users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('validation_requests', schema='app')
